In [2]:
# import packages
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns 
import os
import glob

## Prepare the input

In [3]:
#allB = pd.read_excel('../2023_Clusters/FINAL_tables/FINAL_all_bins_all_clusters.xlsx')
allW = allB[['sample','recovered_genome','final_genomes']]
# rename column
allW = allW.rename(columns={'final_genomes':'best_cluster_genome'})
allW.head()

   sample           recovered_genome    best_cluster_genome
0  V00H9L      V00H9L_vamb.216248.fa  V00H9L_vamb.216248.fa
1  VEZUDR      VEZUDR_vamb.198244.fa  V00H9L_vamb.216248.fa
2  VF9LPS       VF9LPS_maxbin.061.fa  V00H9L_vamb.216248.fa
3  VFK4IA  VFK4IA_vamb.287384_sub.fa  V00H9L_vamb.216248.fa
4  VI72RB       VI72RB_maxbin.021.fa  V00H9L_vamb.216248.fa

In [4]:
bst = pd.read_excel('../2023_Clusters/FINAL_tables/FINAL_only_the_best_genomes_with_2nd_cluster_with_taxa_with_binsNmb_m.xlsx')
bst = bst[['sample_name','genus','best_cluster_genome']]
# rename column
bst = bst.rename(columns={'sample_name':'best_cluster_genome_sample'})
bst_m = bst.drop_duplicates()
bst_m.head()

  best_cluster_genome_sample     genus    best_cluster_genome
0                     VLB6XN      14-2       VLB6XN_256644.fa
1                     VDFRDM      14-2   VDFRDM_metabat.13.fa
2                     V46NG6  1XD42-69  V46NG6_metabat.195.fa
3                     VUXZVX    43-108   VUXZVX_metabat.11.fa
4                     VQQ90U     51-20   VQQ90U_vamb.11929.fa

In [5]:
# make matrix with a 1 & 0
allW = allW.merge(bst_m, how='left', on='best_cluster_genome')
allW['genus_presence'] = 1
# fill NaN genus
allW['genus'] = allW['genus'].fillna('UNKNOWN')
allW = allW.drop_duplicates()
allW.head()

,sample,recovered_genome,best_cluster_genome,best_cluster_genome_sample,genus,genus_presence
0,V00H9L,V00H9L_vamb.216248.fa,V00H9L_vamb.216248.fa,V00H9L,UBA10281,1
1,VEZUDR,VEZUDR_vamb.198244.fa,V00H9L_vamb.216248.fa,V00H9L,UBA10281,1
2,VF9LPS,VF9LPS_maxbin.061.fa,V00H9L_vamb.216248.fa,V00H9L,UBA10281,1
3,VFK4IA,VFK4IA_vamb.287384_sub.fa,V00H9L_vamb.216248.fa,V00H9L,UBA10281,1
4,VI72RB,VI72RB_maxbin.021.fa,V00H9L_vamb.216248.fa,V00H9L,UBA10281,1

In [6]:
allW['cluster'] = allW['genus'] + '--' + allW['recovered_genome']
allW.tail()

,sample,recovered_genome,best_cluster_genome,best_cluster_genome_sample,genus,genus_presence,cluster
70478,VZOC83,VZOC83_vamb.143096.fa,NaN,NaN,UNKNOWN,1,UNKNOWN--VZOC83_vamb.143096.fa
70479,VZOC83,VZOC83_vamb.153642.fa,NaN,NaN,UNKNOWN,1,UNKNOWN--VZOC83_vamb.153642.fa
70480,VZOC83,VZOC83_vamb.162522.fa,NaN,NaN,UNKNOWN,1,UNKNOWN--VZOC83_vamb.162522.fa
70481,VZOC83,VZOC83_vamb.17294.fa,NaN,NaN,UNKNOWN,1,UNKNOWN--VZOC83_vamb.17294.fa
70482,VZOC83,VZOC83_vamb.989.fa,NaN,NaN,UNKNOWN,1,UNKNOWN--VZOC83_vamb.989.fa

In [7]:
# make matrix with a genus name
matrix = allW.pivot(index='cluster', columns='sample', values='genus_presence')
#matrix.to_excel('input/matrix_genus_only.xlsx')

In [9]:
matrix = matrix.fillna(0)

In [10]:
matrix.head()

sample,V00H9L,V010T4,V03HFT,V03ZU2,V0404P,V045JG,V04J9U,V04PTT,V04YHL,V05U4U,...,VZR42V,VZSPJW,VZSQ0C,VZTMOW,VZUFR8,VZWEWM,VZXIHP,VZY957,VZYSJ2,VZZW6V
cluster,,,,,,,,,,,,,,,,,,,,,
14-2--VDFRDM_metabat.13.fa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14-2--VJLSQM_metabat.163.fa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14-2--VLB6XN_256644.fa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1XD42-69--V04J9U_vamb.86341_sub.fa,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1XD42-69--V46NG6_metabat.195.fa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
matrix.to_csv('results/matrix_genus_only.csv')

# Find same genera in same sample

In [ ]:
# read matrix
#matrix1 = pd.read_csv('results/matrix_genus_only.csv', index_col=0)

In [81]:
# prepare data
matrix1 = matrix.reset_index()
# split column values with pattern '--'
patt = matrix1['cluster'].str.split('--', expand=True)
matrix1['genus'] = patt[0]

# Aggregate by Genus and sum the scores
matrix_grouped = matrix1.groupby('genus').sum()
matrix_grouped.to_csv('results/matrix_genus_only_grouped.csv')
matrix_grouped.head()

/var/folders/5j/pvj6k02n3mn9ztpn77vjtfzw0000gn/T/ipykernel_53913/2453865051.py:8: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  matrix_grouped = matrix1.groupby('genus').sum()

sample,V00H9L,V010T4,V03HFT,V03ZU2,V0404P,V045JG,V04J9U,V04PTT,V04YHL,V05U4U,...,VZR42V,VZSPJW,VZSQ0C,VZTMOW,VZUFR8,VZWEWM,VZXIHP,VZY957,VZYSJ2,VZZW6V
genus,,,,,,,,,,,,,,,,,,,,,
14-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1XD42-69,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43-108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51-20,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
Absicoccus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [93]:
# Skip

matrix_grouped.iloc[:, 0:] = matrix_grouped.iloc[:, 0:].replace(1, 0)
matrix_grouped = matrix_grouped[matrix_grouped.iloc[:, 0:].sum(axis=1) > 0]

matrix_grouped

sample,V00H9L,V010T4,V03HFT,V03ZU2,V0404P,V045JG,V04J9U,V04PTT,V04YHL,V05U4U,...,VZR42V,VZSPJW,VZSQ0C,VZTMOW,VZUFR8,VZWEWM,VZXIHP,VZY957,VZYSJ2,VZZW6V
genus,,,,,,,,,,,,,,,,,,,,,
Acetatifactor,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Agathobacter,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
Akkermansia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Alistipes,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
Alistipes_A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UMGS902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
UNKNOWN,0.0,0.0,0.0,0.0,31.0,0.0,45.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Vescimonas,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0
Victivallis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
Zag111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [98]:
# Calculate the sum of values for each column
column_sums = matrix_grouped.sum(axis=0)

# Filter the DataFrame to keep only columns with sum different from 0
matrix_filtered = matrix_grouped[column_sums[column_sums != 0].index]
matrix_filtered

sample,V00H9L,V010T4,V0404P,V04J9U,V04PTT,V04YHL,V05U4U,V06KB2,V0874O,V08XFS,...,VZQLWU,VZQYWY,VZR2LZ,VZR42V,VZSPJW,VZSQ0C,VZUFR8,VZXIHP,VZY957,VZZW6V
genus,,,,,,,,,,,,,,,,,,,,,
Acetatifactor,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Agathobacter,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
Akkermansia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Alistipes,0.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,2.0,0.0,...,0.0,0.0,2.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0
Alistipes_A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UMGS902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
UNKNOWN,0.0,0.0,31.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Vescimonas,0.0,0.0,0.0,4.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0
Victivallis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
Zag111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
matrix_filtered.to_csv('results/matrix_genus_only_grouped_filtered.csv')

In [99]:
# Sort columns by their sum
column_sums = matrix_filtered.sum(axis=0)
matrix_filtered_sorted_columns = matrix_filtered[column_sums.sort_values(ascending=False).index]

# Sort rows by their sum
row_sums = matrix_filtered.sum(axis=1)
matrix_filtered_sorted = matrix_filtered_sorted_columns.loc[row_sums.sort_values(ascending=False).index]

###
matrix_filtered_sorted.to_csv('results/matrix_genus_only_grouped_filtered_sorted.csv')

In [67]:
matrix_filtered_sorted.to_csv('results/matrix_genus_only_grouped_filtered_sorted.csv')

# Collect stats

In [105]:
print('Input bin nuber',len(matrix1))
print('The number of genera represented by several species in at least one sample -',matrix_filtered_sorted.shape[0])
print('The number of samples contains several species from the same genus -',matrix_filtered_sorted.shape[1])

Input bin nuber 70275
The number of genera represented by several species in at least one sample - 132
The number of samples contains several species from the same genus - 1513

In [103]:
1513/1878

0.8056443024494143